/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CheckBox: typeof import('./src/components/CheckBox.vue')['default']
    More: typeof import('./src/components/More.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('./src/components/Skeleton.vue')['default']
    Slider: typeof import('./src/components/Slider.vue')['default']
  }
}
